apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviewer-service
  labels:
    app: reviewer-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reviewer-service
  template:
    metadata:
      labels:
        app: reviewer-service
        tier: backend
    spec:
      containers:
      - name: reviewer-service
        image: reviewer-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9092
        env:
        - name: SERVER_PORT
          value: "9092"
        - name: KAFKA_BOOTSTRAPSERVERS
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_BOOTSTRAPSERVERS
        - name: KAFKA_TOPIC_AZURE_PR_EVENTS
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_TOPIC_AZURE_PR_EVENTS
        - name: KAFKA_SECURITY_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_SECURITY_PROTOCOL
        - name: KAFKA_SASL_MECHANISM
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_SASL_MECHANISM
        - name: KAFKA_SASL_JAAS_CONFIG
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: KAFKA_SASL_JAAS_CONFIG
        - name: ADO_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: ado-config
              key: ADO_BASE_URL
        - name: ADO_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: ado-config
              key: ADO_PROJECT_ID
        - name: ADO_PAT
          valueFrom:
            secretKeyRef:
              name: ado-secrets
              key: ADO_PAT
        - name: AZURE_OPENAI_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: azure-openai-config
              key: AZURE_OPENAI_ENDPOINT
        - name: AZURE_OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: azure-openai-secrets
              key: AZURE_OPENAI_API_KEY
        - name: AZURE_OPENAI_MODEL
          valueFrom:
            configMapKeyRef:
              name: azure-openai-config
              key: AZURE_OPENAI_MODEL
        - name: OTLP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: langfuse-config
              key: OTLP_ENDPOINT
        - name: OTLP_AUTH_HEADER
          valueFrom:
            secretKeyRef:
              name: langfuse-secrets
              key: OTLP_AUTH_HEADER
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "2Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9092
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9092
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: reviewer-service
  labels:
    app: reviewer-service
spec:
  type: ClusterIP
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
  selector:
    app: reviewer-service
