apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-ingest
  labels:
    app: webhook-ingest
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webhook-ingest
  template:
    metadata:
      labels:
        app: webhook-ingest
        tier: frontend
    spec:
      containers:
      - name: webhook-ingest
        image: webhook-ingest:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9091
        env:
        - name: SERVER_PORT
          value: "9091"
        - name: KAFKA_BOOTSTRAPSERVERS
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_BOOTSTRAPSERVERS
        - name: KAFKA_TOPIC_AZURE_PR_EVENTS
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_TOPIC_AZURE_PR_EVENTS
        - name: KAFKA_SECURITY_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_SECURITY_PROTOCOL
        - name: KAFKA_SASL_MECHANISM
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_SASL_MECHANISM
        - name: KAFKA_SASL_JAAS_CONFIG
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: KAFKA_SASL_JAAS_CONFIG
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9091
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9091
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-ingest-service
  labels:
    app: webhook-ingest
spec:
  type: ClusterIP
  ports:
  - port: 9091
    targetPort: 9091
    protocol: TCP
  selector:
    app: webhook-ingest
